const countries = [
  ["D", "DE", "Germany"],
  ["GBR", "GB", "Great Britain"],
  ["PRT", "PT", "Portugal"],
  ["NLD", "NL", "Netherlands"],
  ["DEU", "DE", "Germany"],
  ["FRA", "FR", "France"],
  ["DNK", "DK", "Denmark"],
  ["SWE", "SE", "Sweden"],
  ["CHE", "CH", "Switzerland"],
  ["ITA", "IT", "Italy"],
  ["NOR", "NO", "Norway"],
  ["AUT", "AT", "Austria"],
  ["IRL", "IE", "Ireland"],
  ["FIN", "FI", "Finland"],
  ["BEL", "BE", "Belgium"],
  ["ESP", "ES", "Spain"],
  ["RUS", "RU", "Russia"],
  ["POL", "PL", "Poland"],
  ["CZE", "CZ", "Czech Republic"],
  ["HUN", "HU", "Hungary"],
  ["GRC", "GR", "Greece"],
  ["YUG", "YU", "Federal Republic Of Yugoslavia"],
  ["LUX", "LU", "Luxembourg"],
  ["VAT", "VA", "Vatican City State"],
  ["MLT", "MT", "Malta"],
  ["BGR", "BG", "Bulgaria"],
  ["ROU", "RO", "Romania"],
  ["CYP", "CY", "Cyprus"],
  ["USA", "US", "United States"],
  ["CAN", "CA", "Canada"],
  ["MEX", "MX", "Mexico"],
  ["CUB", "CU", "Cuba"],
  ["ARG", "AR", "Argentina"],
  ["BRA", "BR", "Brazil"],
  ["CHL", "CL", "Chile"],
  ["COL", "CO", "Colombia"],
  ["PER", "PE", "Peru"],
  ["PAN", "PA", "Panama"],
  ["URY", "UY", "Uruguay"],
  ["VEN", "VE", "Venezuela"],
  ["PRI", "PR", "Puerto Rico"],
  ["CHN", "CN", "China"],
  ["IND", "IN", "India"],
  ["VNM", "VN", "Vietnam"],
  ["JPN", "JP", "Japan"],
  ["MMR", "MM", "Myanmar"],
  ["PHL", "PH", "Philippines"],
  ["MYS", "MY", "Malaysia"],
  ["IDN", "ID", "Indonesia"],
  ["PAK", "PK", "Pakistan"],
  ["KOR", "KR", "Korea, Republic Of"],
  ["SGP", "SG", "Singapore"],
  ["NPL", "NP", "Nepal"],
  ["LAO", "LA", "Laos"],
  ["KHM", "KH", "Cambodia"],
  ["LKA", "LK", "Sri Lanka"],
  ["SAU", "SA", "Saudi Arabia"],
  ["ISR", "IL", "Israel"],
  ["LBN", "LB", "Lebanon"],
  ["IRN", "IR", "Iran"],
  ["TUR", "TR", "Turkey"],
  ["BGD", "BD", "Bangladesh"],
  ["SYR", "SY", "Syria"],
  ["IRQ", "IQ", "Iraq"],
  ["KWT", "KW", "Kuwait"],
  ["BRN", "BN", "Brunei Darussalam"],
  ["ZAF", "ZA", "South Africa"],
  ["KEN", "KE", "Kenya"],
  ["EGY", "EG", "Egypt"],
  ["ETH", "ET", "Ethiopia"],
  ["NGA", "NG", "Nigeria"],
  ["ARE", "AE", "United Arab Emirates"],
  ["GIN", "GN", "Guinea"],
  ["AUS", "AU", "Australia"],
  ["NZL", "NZ", "New Zealand"],
  ["PNG", "PG", "Papua New Guinea"],
  ["THA", "TH", "Thailand"],
  ["AFG", "AF", "Afghanistan"],
  ["BHR", "BH", "Bahrain"],
  ["BTN", "BT", "Bhutan"],
  ["JOR", "JO", "Jordan"],
  ["PRK", "KP", "Korea,Democratic People'S Republic Of"],
  ["MDV", "MV", "Maldives"],
  ["MNG", "MN", "Mongolia"],
  ["OMN", "OM", "Oman"],
  ["QAT", "QA", "Qatar"],
  ["YEM", "YE", "Yemen"],
  ["FJI", "FJ", "Fiji"],
  ["KIR", "KI", "Kiribati"],
  ["NRU", "NR", "Nauru"],
  ["SLB", "SB", "Solomon Islands"],
  ["TON", "TO", "Tonga"],
  ["TUV", "TV", "Tuvalu"],
  ["VUT", "VU", "Vanuatu"],
  ["WSM", "WS", "Samoa"],
  ["ALB", "AL", "Albania"],
  ["AND", "AD", "Andorra"],
  ["ZWE", "ZW", "Zimbabwe"],
  ["ISL", "IS", "Iceland"],
  ["LIE", "LI", "Liechtenstein"],
  ["MCO", "MC", "Monaco"],
  ["SMR", "SM", "San Marino"],
  ["DZA", "DZ", "Algeria"],
  ["AGO", "AO", "Angola"],
  ["BEN", "BJ", "Benin"],
  ["BWA", "BW", "Botswana"],
  ["BFA", "BF", "Burkina Fasa"],
  ["BDI", "BI", "Burundi"],
  ["CMR", "CM", "Cameroon"],
  ["CPV", "CV", "Cape Verde"],
  ["CAF", "CF", "Central African Republic"],
  ["TCD", "TD", "Chad"],
  ["COM", "KM", "Comoros"],
  ["COG", "CG", "Congo"],
  ["CIV", "CI", "Cote D'Ivoire"],
  ["DJI", "DJ", "Djibouti"],
  ["GNQ", "GQ", "Equatorial Guinea"],
  ["GAB", "GA", "Gabon"],
  ["GMB", "GM", "Gambia"],
  ["GHA", "GH", "Ghana"],
  ["GNB", "GW", "Guinea Bissau"],
  ["LSO", "LS", "Lesotho"],
  ["LBR", "LR", "Liberia"],
  ["LBY", "LY", "Libyan Arab Jamahiriya"],
  ["MDG", "MG", "Madagascar"],
  ["MWI", "MW", "Malawi"],
  ["MLI", "ML", "Mali"],
  ["MRT", "MR", "Mauritania"],
  ["MUS", "MU", "Mauritius"],
  ["MAR", "MA", "Morocco"],
  ["MOZ", "MZ", "Mozambique"],
  ["NER", "NE", "Niger"],
  ["RWA", "RW", "Rwanda"],
  ["STP", "ST", "Sao Tome And Principe"],
  ["SEN", "SN", "Senegal"],
  ["SYC", "SC", "Seychelles"],
  ["SLE", "SL", "Sierra Leone"],
  ["SOM", "SO", "Somalia"],
  ["SDN", "SD", "Sudan"],
  ["SWZ", "SZ", "Swaziland"],
  ["TZA", "TZ", "Tanzania"],
  ["TGO", "TG", "Togo"],
  ["TUN", "TN", "Tunisia"],
  ["UGA", "UG", "Uganda"],
  ["COG", "CG", "Congo"],
  ["ZMB", "ZM", "Zambia"],
  ["ZIM", "ZW", "Zimbabwe"],
  ["ATG", "AG", "Antigua And Barbuda"],
  ["BHS", "BS", "Bahamas"],
  ["BRB", "BB", "Barbados"],
  ["BLZ", "BZ", "Belize"],
  ["CRI", "CR", "Costa Rica"],
  ["DMA", "DM", "Dominica"],
  ["DOM", "DO", "Dominican Republic"],
  ["SLV", "SV", "El Salvador"],
  ["GRD", "GD", "Grenada"],
  ["GTM", "GT", "Guatemala"],
  ["HTI", "HT", "Haiti"],
  ["HND", "HN", "Honduras"],
  ["JAM", "JM", "Jamaica"],
  ["NIC", "NI", "Nicaragua"],
  ["LCA", "LC", "Saint Lucia"],
  ["VCT", "VC", "Saint Vincent And The Grenadines"],
  ["TTO", "TT", "Trinidad And Tobago"],
  ["BOL", "BO", "Bolivia"],
  ["ECU", "EC", "Ecuador"],
  ["GUY", "GY", "Guyana"],
  ["PRY", "PY", "Paraguay"],
  ["SUR", "SR", "Suriname"],
  ["TLS", "TL", "Timor-Leste"],
  ["UKR", "UA", "Ukraine"],
  ["HKG", "HK", "Hong Kong"],
  ["TWN", "TW", "Taiwan"],
  ["HRV", "HR", "Croatia"],
  ["KAZ", "KZ", "Kazakhstan"],
  ["ARM", "AM", "Armenia"],
  ["AZE", "AZ", "Azerbaijan"],
  ["GEO", "GE", "Georgia"],
  ["KGZ", "KG", "Kyrgzstan"],
  ["TJK", "TJ", "Tajikistan"],
  ["UZB", "UZ", "Uzbekistan"],
  ["MHL", "MH", "Marshall Islands"],
  ["FSM", "FM", "Micronesia, Federated States Of"],
  ["PLW", "PW", "Palau"],
  ["BLR", "BY", "Belarus"],
  ["BIH", "BA", "Bosnia Herzegovina"],
  ["TKM", "TM", "Turkmenistan"],
  ["EST", "EE", "Estonia"],
  ["LVA", "LV", "Latvia"],
  ["LTU", "LT", "Lithuania"],
  ["MKD", "MK", "Macedonia"],
  ["MDA", "MD", "Moldova"],
  ["SVK", "SK", "Slovakia"],
  ["SVN", "SI", "Slovenia"],
  ["ERI", "ER", "Eritrea"],
  ["NAM", "NA", "Namibia"],
  ["BOL", "BO", "Bolivia"],
  ["COK", "CK", "Cook Island"],
  ["TMP", "TP", "East Timor"],
  ["PLT", "PS", "Palestinian Territory"],
  ["SRB", "SF", "Serbia And Montenegro"],
  ["SRB", "RS", "Serbia"],
  ["MNE", "ME", "Montenegro"],
  ["AWB", "AW", "Aruba"],
  ["ABW", "AW", "Aruba"],
  ["UK", "GB", "United Kingdom"]
];
